server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    instance-info-replication-interval-seconds: 10
  server:
    eviction-interval-timer-in-ms: 50000
    wait-time-in-ms-when-sync-empty: 5
